### PR TITLE
Migrate to ReScript v11 / uncurried mode

### LINKED ISSUE #18: Compiler error with ReScript v11 / uncurried mode
I tried upgrading our codebase to ReScript v11 with uncurried mode, but jzon does not compile:
```
We've found a bug for you!
<snip>/node_modules/rescript-jzon/src/Jzon.res:84:47-52

82 ┆ 
83 ┆ let encode = codec => codec.encode
84 ┆ let encodeString = (codec, value) => codec->encode(value)->Js.Json.stri
   ┆ ngify
85 ┆ 
86 ┆ let decode = codec => codec.decode

This uncurried function has type t<'a> => encode<'a>
It is applied with 2 arguments but it requires 1.
```

### PR DESCRIPTION
**Pull request by Minnozz**
Fixes #18

### CODE REVIEW

**Review by seekshiva — APPROVED** [review]

**Comment by Minnozz** [comment]
@seekshiva Thanks for the review! Status is Draft because I haven't updated the tests yet due to incompatibilities in the test dependencies; contributions to this PR are welcome for that

**Comment by Minnozz** [comment]
@seekshiva Tests pass now; do you have merge access?

**Comment by seekshiva** [comment]
@Minnozz I’m not a core developer of jzon. Just that I was able to take changes from your PR into my local fork and it worked well, so I marked it as approved. 

Someone from the jzon core team would have to review and merge this.

**Comment by DZakh** [comment]
I'll ping the maintainer.

**Comment by nkrkv** [comment]
Thank you folks :heart:

**Pull request merged**
